// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/data/catalog.ts
var PHONE = "9696583222";
var WHATSAPP_URL = `https://wa.me/91${PHONE}`;
var EMAIL = "sbjprintingpress32@gmail.com";
var LOCATION = "Kanpur, India";
var WEBSITE_URL = "https://balajigraphics.lovable.app";
var serviceCatalog = [
  {
    id: "logo-design",
    title: "Logo Design",
    shortDescription: "Unique, memorable logos for your brand identity",
    description: "Get a professional, unique logo that represents your brand perfectly. Our designers create memorable logos that make lasting impressions on your customers.",
    icon: "Palette",
    pricing: [
      { name: "Basic", price: "\u20B9499", features: ["2 Logo Concepts", "2 Revisions", "JPG & PNG Files", "Delivery in 3 Days"] },
      { name: "Standard", price: "\u20B9999", features: ["5 Logo Concepts", "Unlimited Revisions", "All File Formats", "Source File", "Delivery in 2 Days"], popular: true },
      { name: "Premium", price: "\u20B91,499", features: ["8 Logo Concepts", "Unlimited Revisions", "All File Formats", "Brand Guidelines", "Social Media Kit", "Priority Delivery"] }
    ]
  },
  {
    id: "poster-design",
    title: "Poster Design",
    shortDescription: "Eye-catching posters for events and promotions",
    description: "Stunning poster designs for events, promotions, festivals, and more. We create vibrant, attention-grabbing posters that communicate your message effectively.",
    icon: "Image",
    pricing: [
      { name: "Basic", price: "\u20B9499", features: ["1 Poster Design", "2 Revisions", "Print-Ready File", "Delivery in 2 Days"] },
      { name: "Standard", price: "\u20B91,499", features: ["3 Poster Designs", "5 Revisions", "Print-Ready + Digital", "Source File"], popular: true },
      { name: "Premium", price: "\u20B92,999", features: ["5 Poster Designs", "Unlimited Revisions", "All Formats", "Multiple Sizes", "Rush Delivery"] }
    ]
  },
  {
    id: "banner-flex-design",
    title: "Banner / Flex Design",
    shortDescription: "Large format banners and flex for maximum visibility",
    description: "Professional banner and flex designs for shops, events, and outdoor advertising. High-impact designs that grab attention from a distance.",
    icon: "Monitor",
    pricing: [
      { name: "Basic", price: "\u20B9699", features: ["1 Banner Design", "2 Revisions", "Print-Ready File", "Standard Size"] },
      { name: "Standard", price: "\u20B91,999", features: ["3 Banner Designs", "5 Revisions", "Multiple Sizes", "Source File"], popular: true },
      { name: "Premium", price: "\u20B93,999", features: ["5 Banner Designs", "Unlimited Revisions", "All Sizes", "Printing Coordination", "Installation Guide"] }
    ]
  },
  {
    id: "social-media-design",
    title: "Social Media Post Design",
    shortDescription: "Engaging social media content that drives results",
    description: "Professional social media post designs for Instagram, Facebook, WhatsApp, and more. Boost your online presence with stunning visuals.",
    icon: "Share2",
    pricing: [
      { name: "Basic", price: "\u20B9299", features: ["5 Post Designs", "2 Revisions Each", "Instagram & Facebook", "Delivery in 3 Days"] },
      { name: "Standard", price: "\u20B9999", features: ["15 Post Designs", "5 Revisions Each", "All Platforms", "Content Calendar"], popular: true },
      { name: "Premium", price: "\u20B92,499", features: ["30 Post Designs", "Unlimited Revisions", "All Platforms", "Story Designs", "Monthly Package"] }
    ]
  },
  {
    id: "wedding-card-design",
    title: "Wedding Card Design",
    shortDescription: "Beautiful wedding invitations that set the tone",
    description: "Elegant and traditional wedding card designs that perfectly capture the joy of your special occasion. Both modern and traditional Indian styles available.",
    icon: "Heart",
    pricing: [
      { name: "Basic", price: "\u20B91,499", features: ["1 Card Design", "2 Revisions", "Print-Ready PDF", "Standard Template"] },
      { name: "Standard", price: "\u20B93,499", features: ["Custom Design", "5 Revisions", "Print + Digital Version", "Matching Envelope"], popular: true },
      { name: "Premium", price: "\u20B96,999", features: ["Fully Custom Design", "Unlimited Revisions", "Complete Set", "RSVP Card", "Thank You Card", "Digital Invite Video"] }
    ]
  },
  {
    id: "visiting-card-design",
    title: "Visiting Card Design",
    shortDescription: "Professional business cards that make an impression",
    description: "Make a great first impression with professionally designed visiting cards. Modern, clean, and memorable designs for your business.",
    icon: "CreditCard",
    pricing: [
      { name: "Basic", price: "\u20B9199", features: ["1 Card Design", "Front Side Only", "2 Revisions", "Print-Ready File"] },
      { name: "Standard", price: "\u20B9299", features: ["2 Design Options", "Front & Back", "5 Revisions", "Source File"], popular: true },
      { name: "Premium", price: "\u20B9399", features: ["4 Design Options", "Front & Back", "Unlimited Revisions", "Letterhead Design", "Printing Coordination"] }
    ]
  },
  {
    id: "promotional-graphics",
    title: "Promotional Graphics",
    shortDescription: "Marketing materials that drive sales",
    description: "Complete promotional graphics package including flyers, brochures, standees, and marketing collateral designed to boost your business.",
    icon: "Megaphone",
    pricing: [
      { name: "Basic", price: "\u20B9799", features: ["1 Design", "2 Revisions", "Print-Ready File", "Single Format"] },
      { name: "Standard", price: "\u20B92,499", features: ["3 Designs", "5 Revisions", "Multiple Formats", "Source Files"], popular: true },
      { name: "Premium", price: "\u20B94,999", features: ["Complete Package", "Unlimited Revisions", "All Formats", "Print Coordination", "Digital Versions"] }
    ]
  }
];
var portfolioCatalog = [
  { id: "1", title: "Restaurant Logo", category: "Logo Design" },
  { id: "2", title: "Festival Poster", category: "Poster Design" },
  { id: "3", title: "Shop Banner", category: "Banner Design" },
  { id: "4", title: "Instagram Posts", category: "Social Media" },
  { id: "5", title: "Wedding Invitation", category: "Wedding Card" },
  { id: "6", title: "Business Cards", category: "Visiting Card" }
];
var testimonials = [
  { id: "1", name: "Rajesh Sharma", business: "Sharma Electronics", text: "Balaji Graphics designed our shop banner and visiting cards. Excellent quality and very affordable prices. Highly recommended!", rating: 5 },
  { id: "2", name: "Priya Patel", business: "Patel Sarees", text: "Beautiful social media designs for our saree shop. Our Instagram followers doubled in just 2 months! Thank you Balaji Graphics.", rating: 5 },
  { id: "3", name: "Amit Verma", business: "Verma Sweets", text: "They designed our wedding cards and they were absolutely stunning. Everyone complimented the design. Will definitely order again.", rating: 5 },
  { id: "4", name: "Sunita Agarwal", business: "Agarwal Traders", text: "Professional logo design at a very reasonable price. The team is responsive and delivers on time. Very happy with the service.", rating: 4 }
];

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List all graphic design services offered by Balaji Graphics, with a short description for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = serviceCatalog.map((s) => ({
      id: s.id,
      title: s.title,
      summary: s.shortDescription,
      startingPrice: s.pricing[0]?.price
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/tools/get-service.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var get_service_default = defineTool2({
  name: "get_service",
  title: "Get service details",
  description: "Get the full description and all pricing packages for one Balaji Graphics service, by its id (use list_services to find ids).",
  inputSchema: {
    id: z.string().describe("Service id, e.g. logo-design or wedding-card-design.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const service = serviceCatalog.find((s) => s.id === id.trim().toLowerCase());
    if (!service) {
      throw new ToolError(
        `No service with id "${id}". Available ids: ${serviceCatalog.map((s) => s.id).join(", ")}`
      );
    }
    const detail = { ...service, url: `${WEBSITE_URL}/services/${service.id}` };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: { service: detail }
    };
  }
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_pricing_default = defineTool3({
  name: "get_pricing",
  title: "Get pricing",
  description: "Get pricing packages for Balaji Graphics. Returns every service when no id is given, or one service's packages when an id is provided.",
  inputSchema: {
    id: z2.string().optional().describe("Optional service id to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const wanted = id?.trim().toLowerCase();
    const rows = serviceCatalog.filter((s) => !wanted || s.id === wanted).map((s) => ({ id: s.id, title: s.title, pricing: s.pricing }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { pricing: rows }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get Balaji Graphics contact details and a ready-to-use WhatsApp ordering link, optionally prefilled with a message about a service.",
  inputSchema: {
    serviceId: z3.string().optional().describe("Optional service id to prefill the WhatsApp enquiry message.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ serviceId }) => {
    const service = serviceId ? serviceCatalog.find((s) => s.id === serviceId.trim().toLowerCase()) : void 0;
    const whatsappUrl = service ? `${WHATSAPP_URL}?text=${encodeURIComponent(`Hi Balaji Graphics, I'm interested in ${service.title}.`)}` : WHATSAPP_URL;
    const info = {
      business: "Balaji Graphics",
      phone: PHONE,
      whatsappUrl,
      email: EMAIL,
      location: LOCATION,
      website: WEBSITE_URL
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-portfolio.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_portfolio_default = defineTool5({
  name: "list_portfolio",
  title: "List portfolio and reviews",
  description: "List Balaji Graphics portfolio work samples and customer testimonials shown on the website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      portfolioUrl: `${WEBSITE_URL}/portfolio`,
      portfolio: portfolioCatalog,
      testimonials
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "balaji-graphics",
  title: "Balaji Graphics",
  version: "0.1.0",
  instructions: "Public tools for Balaji Graphics, a graphic design studio in Kanpur, India. Use `list_services` to see all design services, `get_service` for full details of one service, `get_pricing` for package prices, `list_portfolio` for work samples and customer reviews, and `get_contact_info` for phone, email, and a WhatsApp ordering link. All data is public website information.",
  tools: [list_services_default, get_service_default, get_pricing_default, list_portfolio_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
